# Run hooks via shell
shell = "sh -c '{}'"

# --- i3 ----------------------------------------------------------
[[item]]
file = "~/.config/i3/config"
template = "i3"
subtemplate = "default"
start = "# Start flavours"
end   = "# End flavours"
rewrite = false
# Optional: reload i3 after inject
hook = "i3-msg reload"
light = false

# --- Xresources --------------------------------------------------
[[item]]
file = "~/.Xresources"
template = "xresources"
start = "! Start flavours"
end   = "! End flavours"
hook = "xrdb -load ~/.Xresources"

# --- YouTube Music (custom template path OK) ---------------------
[[item]]
file = "~/.config/YouTube Music/darcula.css"
template = "/home/duane/.local/share/flavours/base16/templates/youtube-music/"
start = "/* Start flavours */"
end   = "/* End flavours */"

# --- GTK (FlatColor) --------------------------------------------
[[item]]
file = "~/.themes/FlatColor/colors3"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = true
hook = "gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme FlatColor"

[[item]]
file = "~/.themes/FlatColor/colors2"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
rewrite = true

# --- Kitty -------------------------------------------------------
[[item]]
file = "~/.config/kitty/kitty.conf"
template = "kitty"
subtemplate = "default-256"

# --- Rofi --------------------------------------------------------
[[item]]
file = "~/.config/rofi/dc-theme.rasi"
template = "rofi"
start = "/* Start flavours */"
end   = "/* End flavours */"

# --- Dunst --------------------------------------------------------
[[item]]
file = "~/.config/dunst/dunstrc"
template = "dunst"
start = "# Start flavours"
end   = "# End flavours"
rewrite = false

# Geany colourscheme generated by the template above
[[items]]
file = "~/.config/geany/colorschemes/base16-current.conf"
template = "geany"
rewrite = true
# Ask running Geany to reload the scheme (fails harmlessly if not running)
posthook = "pkill -USR1 geany || true"

# Generate a tiny CSS override that ONLY sets Thunar BG to current base00
[[items]]
file = "~/.config/gtk-3.0/gtk.css"
template = "gtk3"
subtemplate = "default"
start = "/* Start flavours */"
end   = "/* End flavours */"
rewrite = false
posthook = "thunar -q || true"


[[items]]
file = "~/.config/cava/config"
template = "cava"
subtemplate = "default"
start = "# Start flavours"
end   = "# End flavours"
rewrite = false
posthook = "pkill -USR1 cava || true"

[[items]]
file = "/home/duane/.local/share/flavours/base16/templates/guake/templates/default.mustache"
template = "guake"
rewrite = true





