[files]
current_page=8
recent_files=/home/duane/.config/picom.conf;/home/duane/.config/polybar/scripts/vol_status.sh;/home/duane/.config/polybar/scripts/wifi_status.sh;/home/duane/git/tabler-icons/packages/icons-webfont/README.md;/home/duane/git/tabler-icons/README.md;/home/duane/.config/rofi/wifi-menu.rasi;/usr/bin/rofi-wifi-menu;/home/duane/.config/rofi/style-power.rasi;/home/duane/.config/polybar/scripts/bt_status.sh;/home/duane/.config/polybar/scripts/rofi-bluetooth.sh;
recent_projects=
FILE_NAME_0=5330;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.config%2Fi3%2Fconfig;0;4
FILE_NAME_1=348;YAML;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.local%2Fshare%2Fflavours%2Fbase16%2Fschemes%2Ftwilight%2Ftwilight.yaml;0;4
FILE_NAME_2=1260;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.config%2Fpolybar%2Fconfig.ini;0;4
FILE_NAME_3=5749;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.config%2Fpolybar%2Fmodules.ini;0;4
FILE_NAME_4=1564;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.config%2Fpicom.conf;0;4
FILE_NAME_5=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.config%2Fpolybar%2Fscripts%2Fwifi_status.sh;0;4
FILE_NAME_6=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.config%2Fpolybar%2Fscripts%2Fvol_status.sh;0;4
FILE_NAME_7=1047;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.config%2Fpolybar%2Fscripts%2Fbt_status.sh;0;4
FILE_NAME_8=0;None;0;EUTF-8;1;1;0;%2Fhome%2Fduane%2F.Xresources;0;4

[project]
session_file=
project_file_path=/home/duane/projects

[geany]
treeview_position=156
msgwindow_position=368
geometry=20;75;1250;1345;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=1626
position_find_y=693
position_replace_x=315
position_replace_y=684
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;

[VTE]
last_dir=/home/duane
