[settings]
screenchange-reload = true
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = true
enable-ipc = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[global/wm]
margin-bottom = 0
margin-top = 0
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/left]
monitor = HDMI-A-1
dpi-x = 100
dpi-y = 100
monitor-strict = true
override-redirect = true
wm-restack = i3
dim-value = 1.0
wm-name = i3-wm
enable-ipc = true
bottom = false
fixed-center = true
width = 2520
height = 35
offset-x = 20
offset-y = 20
background = ${color.background}
foreground = ${color.foreground}
radius = 0
border-size = 0
border-color = ${color.base02}

underline-size = 5
overline-size = 5
underline-color = ${color.background}

; border-left-size = 3
; border-right-size = 3
; border-bottom-size = 5
; border-top-size = 5
; border-right-color = ${color.base02}
; border-bottom-color = ${color.base02}
; border-top-color = ${color.base02}

padding-right = 5
padding-left = 5
module-margin-left = 2
module-margin-right = 2

font-0 = "League Spartan:style=Medium:pixelsize=11;3"
font-1 = "Weather Icons:size=9"
font-2 = "Hack Nerd Font:style=Regular,Book:size=10:antialias=true;3"
font-3 = "MaterialIcons:size=19"
font-4 = "Hack Nerd Font:style=Regular:size=13:antialias=true;3"
font-5 = "Noto Color Emoji:scale=10;3"
font-6 = "SF Mono:style=Regular:size=10;3"

modules-left = updates now ewmh now music scroll 
modules-center =  date now time now temp 
modules-right =  temps now bluetooth volume wifi 


tray-position = none
tray-detached = true
tray-maxsize = 16
tray-offset-x = -0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1
tray-background = ${color.background}
tray-foreground = ${color.background}
# tray-underline-color = ${color.background}
# tray-underline-size = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
